version: '3'

services:
  mysql:
    image: mysql:5.7.16
    platform: linux/x86_64
    container_name: app_mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: health_app
      MYSQL_DATABASE: health_app
      MYSQL_USER: health_app
      MYSQL_PASSWORD: health_app
    # volumes:
      # - ./mysql/data:/var/lib/mysql
      # - ./mysql_conf:/etc/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  redis:
    image: redis:alpine
    platform: linux/x86_64
    container_name: app_redis
    # restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
